WebApplication3/ViewModels/Login.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;

namespace WebApplication3.ViewModels
{
    public class Login
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType (DataType.Password)]
        public string Password { get; set; }

        public bool RememberMe { get; set; }  
    }
}

WebApplication3/ViewModels/Register.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;

namespace WebApplication3.ViewModels
{
    public class Register
	{
		[Required(ErrorMessage = "First Name is required")]
		[DataType(DataType.Text)]
		public string FirstName { get; set; }

		[Required(ErrorMessage = "Last Name is required")]
		[DataType(DataType.Text)]
		public string LastName { get; set; }

		[Required(ErrorMessage = "Gender is required")]
		[DataType(DataType.Text)]
		public string Gender { get; set; }

		[Required(ErrorMessage = "NRIC is required")]
		[RegularExpression("^[A-Za-z0-9]*$", ErrorMessage = "NRIC must be alphanumeric")]
		public string NRIC { get; set; }

		[Required(ErrorMessage = "Email Address is required")]
		[DataType(DataType.EmailAddress)]
		[EmailAddress(ErrorMessage = "Invalid Email Address")]
		public string Email { get; set; }

		[Required(ErrorMessage = "Password is required")]
		[DataType(DataType.Password)]
		[MinLength(12, ErrorMessage = "Password must be at least 12 characters long")]
		public string Password { get; set; }

		[Required]
		[DataType(DataType.Password)]
		[Compare(nameof(Password), ErrorMessage = "Password and confirmation password do not match")]
		public string ConfirmPassword { get; set; }

		[Required(ErrorMessage = "Birth date is required")]
		[DataType(DataType.Date)]
		public DateTime DateOfBirth { get; set; }

        [Required(ErrorMessage = "Please select membership level")]
		[RegularExpression(@"^[^\s]+(\s+[^\s]+)*$", ErrorMessage = "Special characters are not allowed")]
		public string WhoAmI { get; set; }

	}
}

WebApplication3/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebApplication3.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebApplication3/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication3.Pages
{
    [Authorize]
    public class IndexModel : PageModel
    {
            private readonly ILogger<IndexModel> _logger;

            public IndexModel(ILogger<IndexModel> logger)
            {
                _logger = logger;
            }

        public void OnGet()
        {

        }
    }
}

WebApplication3/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.IO;
using System.Net;
using System.Text.Json;
using System.Threading.Tasks;
using WebApplication3.Model;
using WebApplication3.ViewModels;

namespace WebApplication3.Pages
{
	public class LoginModel : PageModel
	{
		[BindProperty]
		public Login LModel { get; set; }

		private readonly SignInManager<ApplicationUser> signInManager;
		private readonly IHttpContextAccessor httpContextAccessor;

		public LoginModel(SignInManager<ApplicationUser> signInManager, IHttpContextAccessor httpContextAccessor)
		{
			this.signInManager = signInManager;
			this.httpContextAccessor = httpContextAccessor;
		}

		public void OnGet()
		{
		}

		public async Task<IActionResult> OnPostAsync()
		{
			if (ModelState.IsValid)
			{
				if (!ValidateCaptcha())
				{
					ModelState.AddModelError("LModel.Email", "Please validate the CAPTCHA to prove that you are a human.");
					return Page();
				}

				var user = await signInManager.UserManager.FindByNameAsync(LModel.Email);

				if (user != null)
				{
					var identityResult = await signInManager.PasswordSignInAsync(user, LModel.Password,
						LModel.RememberMe, lockoutOnFailure: true);

					if (identityResult.Succeeded)
					{
						httpContextAccessor.HttpContext.Session.SetString("UserId", user.Id);

						var existingUserId = httpContextAccessor.HttpContext.Session.GetString("UserId");
						if (existingUserId != null && existingUserId != user.Id)
						{
							ModelState.AddModelError("LModel.Email", "Multiple logins detected. Please logout from other sessions.");
							await signInManager.SignOutAsync();
							return Page();
						}

						return RedirectToPage("Index");
					}
					if (identityResult.IsLockedOut)
					{
						ModelState.AddModelError("LModel.Email", "Account locked out. Please try again later.");
						return Page();
					}
				}
				ModelState.AddModelError("LModel.Email", "Username or Password incorrect");
			}
			return Page();
		}

		public bool ValidateCaptcha()
		{
			bool result = true;

			string captchaResponse = Request.Form["g-recaptcha-response"];

			HttpWebRequest req = (HttpWebRequest)WebRequest.Create("https://www.google.com/recaptcha/api/siteverify?secret=6LeUl2EpAAAAAMjWxA8uRShAl8ZkI1s9_dtBbBmi &response=" + captchaResponse);

			try
			{
				using (WebResponse wResponse = req.GetResponse())
				{
					using (StreamReader readStream = new StreamReader(wResponse.GetResponseStream()))
					{
						string jsonResponse = readStream.ReadToEnd();

						MyObject jsonObject = JsonSerializer.Deserialize<MyObject>(jsonResponse);
						result = Convert.ToBoolean(jsonObject.success);
					}
				}
				return result;
			}
			catch (WebException ex)
			{
				throw ex;
			}
		}
	}
}

WebApplication3/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication3.Model;

namespace WebApplication3.Pages
{
    public class LogoutModel : PageModel
    {

        private readonly SignInManager<ApplicationUser> signInManager;

        public LogoutModel(SignInManager<ApplicationUser> signInManager)
        {
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            HttpContext.Session.Clear();
            return RedirectToPage("Login");
        }

        public async Task<IActionResult> OnPostDontLogoutAsync()
        {
            return RedirectToPage("Index");
        }
    }
}

WebApplication3/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication3.Pages
{
    [Authorize]
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebApplication3/Pages/Register.cshtml.cs
using Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MimeKit;
using WebApplication3.Model;
using WebApplication3.ViewModels;
using MailKit.Net.Smtp;
using MimeKit;

namespace WebApplication3.Pages
{
    public class RegisterModel : PageModel
    {

        private UserManager<ApplicationUser> userManager { get; }
        private SignInManager<ApplicationUser> signInManager { get; }

        [BindProperty]
        public Register RModel { get; set; }

        public RegisterModel(UserManager<ApplicationUser> userManager,
        SignInManager<ApplicationUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }



        public void OnGet()
        {
        }


        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                // Check if email exists
                var existingUser = await userManager.FindByEmailAsync(RModel.Email);
                if (existingUser != null)
                {
                    ModelState.AddModelError("RModel.Email", "Email address is already in use");
                }
                var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
                var protector = dataProtectionProvider.CreateProtector("MySecretKey");

                var user = new ApplicationUser()
                {
                    UserName = RModel.Email,
                    Email = RModel.Email,
                    FirstName = RModel.FirstName,
                    LastName = RModel.LastName,
                    Gender = RModel.Gender,
                    NRIC = protector.Protect(RModel.NRIC),
                    DateOfBirth = RModel.DateOfBirth,
                    WhoAmI = RModel.WhoAmI
                };
                var result = await userManager.CreateAsync(user, RModel.Password);
                if (result.Succeeded)
                {
                    await signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToPage("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return Page();
        }
    }
}

WebApplication3/Pages/UserDetails.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity;
using WebApplication3.Model;
using Microsoft.AspNetCore.DataProtection;

namespace WebApplication3.Pages
{
    [Authorize]
    public class UserDetailsModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public UserDetailsModel(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public ApplicationUser ApplicationUser { get; private set; }

        public async Task<IActionResult> OnGetAsync()
        {
            // Retrieve the currently logged-in user
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            // Decrypt the NRIC number
            var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
            var protector = dataProtectionProvider.CreateProtector("MySecretKey");
            user.NRIC = protector.Unprotect(user.NRIC);

            ApplicationUser = user;
            return Page();
        }
    }
}

WebApplication3/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication3/Pages/Login.cshtml
@page
@model WebApplication3.Pages.LoginModel
@{
}

<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Login </h1>

			<form method="post">

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Email">Email Address</label>
					<input type="Text" asp-for="LModel.Email" class="form-control" />
					<span asp-validation-for="LModel.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Password">Password</label>
					<input type="password" asp-for="LModel.Password" class="form-control" />
					<span asp-validation-for="LModel.Password" class="text-danger"></span>
				</div>

				<div class="mb-3 form-check">
					<input type="checkbox" asp-for="LModel.RememberMe" class="form-check-input" />
					<label class="form-check-label" asp-for="LModel.RememberMe">Remember Me?</label>
				</div>

				<div class="mb-3">
					<button type="submit" class="btn btn-primary">Login</button>
				</div>

				<div class="g-recaptcha" data-sitekey="6LeUl2EpAAAAADuqjuzw2K7F6wnXoe4BzXxbA2GK"></div>

			</form>
		</div>
	</div>
</div>

@section Scripts {

	<script src="https://www.google.com/recaptcha/api.js"></script>

}

WebApplication3/Pages/Logout.cshtml
@page
@model WebApplication3.Pages.LogoutModel
@{
}

<form method="post">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-4">
                <p> Are you sure you want to logout? </p>
                <p>
                    <button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
                    <button class="btn btn-light ml-5 border-dark" asp-page-handler="DontLogout">No</button>
                </p>
            </div>
        </div>
    </div>
</form>

WebApplication3/Pages/Register.cshtml
@page
@model WebApplication3.Pages.RegisterModel

@using Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage
@using Microsoft.AspNetCore.DataProtection
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc
@using Microsoft.AspNetCore.Mvc.RazorPages
@using WebApplication3.Model
@using WebApplication3.ViewModels
@using Microsoft.AspNetCore.Http
@using Microsoft.Extensions.Configuration



@{
    var genders = new List<SelectListItem>
    {
        new SelectListItem { Value = "Male", Text = "Male" },
        new SelectListItem { Value = "Female", Text = "Female" },
        new SelectListItem { Value = "Other", Text = "Other" }
    };

    var whoAmIOptions = new List<SelectListItem>
    {
        new SelectListItem { Value = "Tier 1", Text = "Tier 1 Member" },
        new SelectListItem { Value = "Tier 2", Text = "Tier 2 Member" },
        new SelectListItem { Value = "Tier 3", Text = "Tier 3 Member" }
    };
}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-6">
            <h1 class="mb-3">Register</h1>

            <form method="post" enctype="multipart/form-data" onsubmit="return validatePassword();">

                <div class="row">
                    <div class="col-md-6 mb-3">               
                        <label class="form-label" asp-for="RModel.FirstName">First Name</label>
                        <input type="text" asp-for="RModel.FirstName" class="form-control" />
                        <span asp-validation-for="RModel.FirstName" class="text-danger"></span>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label class="form-label" asp-for="RModel.LastName">Last Name</label>
                        <input type="text" asp-for="RModel.LastName" class="form-control" />
                        <span asp-validation-for="RModel.LastName" class="text-danger"></span>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label class="form-label" asp-for="RModel.Password">Password</label>
                        <input type="password" asp-for="RModel.Password" class="form-control" />
                        <span asp-validation-for="RModel.Password" class="text-danger"></span>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label class="form-label" asp-for="RModel.ConfirmPassword">Confirm Password</label>
                        <input type="password" asp-for="RModel.ConfirmPassword" class="form-control" />
                        <span asp-validation-for="RModel.ConfirmPassword" class="text-danger"></span>
                    </div>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.Email">Email Address</label>
                    <input type="email" asp-for="RModel.Email" class="form-control" />
                    <span asp-validation-for="RModel.Email" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label">Gender</label>
                    <select asp-for="RModel.Gender" class="form-control">
                        <option value="">Select Gender</option>
                        @foreach (var gender in genders)
                        {
                            <option value="@gender.Value">@gender.Text</option>
                        }
                    </select>
                    <span asp-validation-for="RModel.Gender" class="text-danger"></span>
                </div>  

                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label class="form-label" asp-for="RModel.NRIC">NRIC</label>
                        <input type="text" asp-for="RModel.NRIC" class="form-control" />
                        <span asp-validation-for="RModel.NRIC" class="text-danger"></span>
                    </div>

                    <div class="col-md-6 mb-3">
                        <label class="form-label" asp-for="RModel.DateOfBirth">Date of Birth</label>
                        <input type="date" asp-for="RModel.DateOfBirth" class="form-control" />
                        <span asp-validation-for="RModel.DateOfBirth" class="text-danger"></span>
                    </div>
                </div>

                <div class="mb-3">
                    <label class="form-label">Who Am I</label>
                    <select asp-for="RModel.WhoAmI" class="form-control">
                        <option value="">Select Who Am I</option>
                        @foreach (var option in whoAmIOptions)
                        {
                            <option value="@option.Value">@option.Text</option>
                        }
                    </select>
                    <span asp-validation-for="RModel.WhoAmI" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Register</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {

    <script>
        function validatePassword() {
            var password = document.getElementById("RModel_Password").value;
            var regex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\da-zA-Z]).{12,}$/;
            if (!regex.test(password)) {
                alert("Password must contain at least 12 characters, including at least one lowercase letter, one uppercase letter, one number, and one special character.");
                return false;
            }
            return true;
        }
    </script>
}

WebApplication3/Pages/UserDetails.cshtml
@page
@model UserDetailsModel
@{
    ViewData["Title"] = "User Details";
}

<h1>User Details</h1>

<div>
    <h3>Welcome, @Model.ApplicationUser.FirstName!</h3>
    <p><strong>Email:</strong> @Model.ApplicationUser.Email</p>
    <p><strong>First Name:</strong> @Model.ApplicationUser.FirstName</p>
    <p><strong>Last Name:</strong> @Model.ApplicationUser.LastName</p>
    <p><strong>NRIC:</strong> @Model.ApplicationUser.NRIC</p>
</div>